from enum import Enum


class Status(Enum):
    EN_COUR = "EN_COUR"
    EN_VALIDATION = "EN_VALIDATION"
    TERMINE = "TERMINE"
    SIMULATION = "SIMULATION"
    SIMULATION_TERMINE = "SIMULATION_TERMINE"
